apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      dbName: bucket
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token token'